import { Room } from '@/types/database';

export const DEFAULT_ROOMS: Room[] = [
  {
    id: 'room-g1',
    room_number: 'G1',
    floor: 0,
    base_rent: 0,
    security_deposit: 0,
    status: 'VACANT',
    capacity: 2,
    current_occupancy: 0,
    can_someone_get_in: true,
    notes: '',
  },
  {
    id: 'room-2a',
    room_number: '2A',
    floor: 2,
    base_rent: 0,
    security_deposit: 0,
    status: 'VACANT',
    capacity: 2,
    current_occupancy: 0,
    can_someone_get_in: true,
    notes: '',
  },
  {
    id: 'room-2b',
    room_number: '2B',
    floor: 2,
    base_rent: 0,
    security_deposit: 0,
    status: 'VACANT',
    capacity: 2,
    current_occupancy: 0,
    can_someone_get_in: true,
    notes: '',
  },
  {
    id: 'room-3a',
    room_number: '3A',
    floor: 3,
    base_rent: 0,
    security_deposit: 0,
    status: 'VACANT',
    capacity: 2,
    current_occupancy: 0,
    can_someone_get_in: true,
    notes: '',
  },
  {
    id: 'room-3b',
    room_number: '3B',
    floor: 3,
    base_rent: 0,
    security_deposit: 0,
    status: 'VACANT',
    capacity: 2,
    current_occupancy: 0,
    can_someone_get_in: true,
    notes: '',
  },
  {
    id: 'room-p1',
    room_number: 'P1',
    floor: 4,
    base_rent: 0,
    security_deposit: 0,
    status: 'VACANT',
    capacity: 2,
    current_occupancy: 0,
    can_someone_get_in: true,
    notes: '',
  },
];
